wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.32
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.10
alpha:
  desc: null
  value: 0.2
batch_size:
  desc: null
  value: 128
checkpoint:
  desc: null
  value: cross_entropy_r50_ResNet34_sim
crop:
  desc: null
  value: 4
data_dir:
  desc: null
  value: ./data/
eps:
  desc: null
  value: 0.99
gpuid:
  desc: null
  value: 1
id:
  desc: null
  value: MLNT_r50_ResNet34_sim
image_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.2
meta_lr:
  desc: null
  value: 0.4
mid_iter:
  desc: null
  value: 2000
noise_rate:
  desc: null
  value: 0.5
num_epochs:
  desc: null
  value: 120
num_fast:
  desc: null
  value: 10
num_workers:
  desc: null
  value: 10
optimizer_type:
  desc: null
  value: SGD
perturb_ratio:
  desc: null
  value: 0.5
pretrained:
  desc: null
  value: false
seed:
  desc: null
  value: 7
shuffle:
  desc: null
  value: true
start_epoch:
  desc: null
  value: 80
start_iter:
  desc: null
  value: 500
